---
functional:
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать
    подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и
    просматривать содержимое корзины
  - Пользователь должен иметь возможность искать товары по ключевому слову или
    категории
non-functional:
  - Сайт должен быть доступен на различных устройствах
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт должен иметь мобильную версию
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для
    скорости работы
implicit:
  - Пользователи ожидают, что интерфейс будет легким для понимания и
    использования даже без документации
  - Переключение между языками должно проходить без ошибок и с корректным
    отображением текстов
  - Пользователям нужно дать возможность авторизоваться(регистрироваться) со
    всеми необходимыми данными(мобильный телефон, e-mail) для получения
    информации о поступление товара
  - Сайт должен быть адаптирован для людей с ограниченными возможностями
  - Ожидается, что приложение собирает только необходимую информацию и не
    злоупотребляет доверием пользователя
  - Пользователи должны быть уведомлены о сборе данных и получать возможность
    управлять своими конфиденциальными настройками
  - Добавлять товар в корзину и формлять заказ могут только зарегистрированные и
    авторизованные пользователи
  - Запретить добавление товаров в корзину которых нет в наличии
  - У пользователя должна быть возможность отмена заказа с возвратом денежных
    средств
